import Tabs from '@theme/Tabs'
import TabItem from '@theme/TabItem'
import { Card, MainText, RelatedTable, HeadlessTable } from '@site/src/components'
import { getHookDataByTitle } from '/utils/getHooks'
const {title, description, content, doc} = getHookDataByTitle('useErrorBoundary')

<head>
  <title>{title}</title>
  <meta name="description" content={description} />
</head>

<MainText>
{description}
</MainText>

<MainText>
<h1>useErrorBoundary</h1>
Use any element as an error boundary and render a fallback component on errors
</MainText>





## Usage

<Tabs>


<TabItem value='advanced' label='Advanced'>

```tsx live
function CustomBoundary() {

    const fallback = ({error, resetErrorBoundary}) => {
        return (
            <div className='error'>
                <h3>Fallback Component</h3>
                <p>Name: {error.name}</p>
                <p>Message: {error.message}</p>
            </div>
        )
    }

    const ThrowError = () => {
        throw new Error('An error!!')
        return <div />
    }


    const ErrorBoundary = useErrorBoundary({ fallback })

    return (
        <ErrorBoundary>
            <ThrowError />
        </ErrorBoundary>
    )
}
```

</TabItem>

<TabItem value='full' label='Full'>

```js live
function CustomBoundary() {

    const [shouldThrow, setShouldThrow] = useState(false)

    const fallback = ({error, resetErrorBoundary}) => {
        return (
            <div className='error'>
                <h3>Fallback Component</h3>
                <p>Name: {error.name}</p>
                <p>Message: {error.message}</p>
                <p>Stack Length: {error.stack.length}</p>
                <button onClick={resetErrorBoundary}>Try again</button>
            </div>
        )
    }

    const ThrowError = () => {
        throw new Error('An error!!')
        return <div />
    }

    const ErrorBoundary = useErrorBoundary({
        fallback,
        handleError: (error: Error, info: React.ErrorInfo) => console.log('handleError:', { error, info }),
        handleReset: () => setShouldThrow(false)
    })

    return (
        <ErrorBoundary>
            {shouldThrow && <ThrowError />}
            <button onClick={() => setShouldThrow(true)} >Throw!</button>
        </ErrorBoundary>
    )
}
```

</TabItem>
</Tabs>











<br />
<hr />
{/* ============================================================================ */}


## API 

Values used for initial state and internal settings are provided as a config
object 


### Config Example

```ts
const ErrorBoundary = useErrorBoundary({
    fallback,
    handleError,
    handleReset
})
```


### Return Values

<HeadlessTable code={1} items={[
    ['@ErrorBoundary','React.Fragment','A React component used to wrap child components that may throw']
]}/>


### Interfaces

```ts
type T_UseErrorBoundaryConfig = {
    children?: React.ReactNode;
    fallback?: React.JSXElementConstructor<any>;
    handleError?: ErrorHandler;
    handleReset?: Function;
}

type T_UseErrorBoundary = (config?: T_UseErrorBoundaryConfig) => React.JSXElementConstructor<any>
```











<br />
<hr />
{/* ============================================================================ */}



## Internal

<small>
The Catch function is a higher-order component that returns a new component with error handling 
capabilities. It takes in an error handling component and an optional error handler function, and 
returns a new component with a componentDidCatch lifecycle method that catches any errors thrown by 
its child components. If an error is caught, it updates the state to include the error and calls 
the error handler function if provided.

The useErrorBoundary hook uses the Catch function to create an error boundary component that can 
be used to catch errors in child components. It takes in a configuration object with optional 
children, fallback, handleError, and handleReset properties. If an error is caught by the boundary 
component, it updates the state to include the error and returns either the provided fallback 
component or a default error component. If there is no error, it simply returns the child components. 
The hook returns a JSX element constructor that can be used as a wrapper around components that
 need error handling capabilities.
</small>

<RelatedTable hooks={['useEffect', 'useRef', 'useMemo']} />


<br />
<hr />
{/* ============================================================================ */}



## Related Hooks


<RelatedTable hooks={['useLogWall']} />

<!-- ignore-hook-methods -->